#! /usr/local/bin/node

const fs = require('fs')
const command = process.argv[2]

const add = require('./commands/add')
const list = require('./commands/list')
const complete = require('./commands/complete')

switch (command) {
  case 'add':
    const todo = process.argv[3]
    add()
    break;
  case 'list':
    list()
    break;
  case 'complete':
  case 'delete':
    complete()
    break;
  default:

}
